export const fetchGenreMock = {
	results: [
		{
			adult: false,
			backdrop_path: '/uUiIGztTrfDhPdAFJpr6m4UBMAd.jpg',
			genre_ids: [14, 28, 878],
			id: 634492,
			original_language: 'en',
			original_title: 'Madame Web',
			overview:
				'Forced to confront revelations about her past, paramedic Cassandra Webb forges a relationship with three young women destined for powerful futures...if they can all survive a deadly present.',
			popularity: 441.913,
			poster_path: '/rULWuutDcN5NvtiZi4FRPzRYWSh.jpg',
			release_date: '2024-02-14',
			title: 'Madame Web',
			video: false,
			vote_average: 5.344,
			vote_count: 247,
		},
		{
			adult: false,
			backdrop_path: '/uhUO7vQQKvCTfQWubOt5MAKokbL.jpg',
			genre_ids: [878, 12],
			id: 693134,
			original_language: 'en',
			original_title: 'Dune: Part Two',
			overview:
				'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
			popularity: 461.426,
			poster_path: '/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
			release_date: '2024-02-27',
			title: 'Dune: Part Two',
			video: false,
			vote_average: 8.7,
			vote_count: 14,
		},
		{
			adult: false,
			backdrop_path: '/gc3TagLk8cYUFM5x4ERM3VIWcLX.jpg',
			genre_ids: [28, 878],
			id: 1241534,
			original_language: 'en',
			original_title: 'シン・スパイダーマン',
			overview:
				"For 45 years, Takuya Yamashiro has been known as the one true Spider-Man. In this New Theatrical Version, Takuya's life is totally changed when the Iron Cross Army takes the life of his father. Now imbued with the rage and power from Planet Spider, he must rise up and take down the Iron Cross Army's evil leader, Professor Monster as SPIDER-MAN.",
			popularity: 2.611,
			poster_path: '/h2ncfhfr3bwdtZ2CVtC1ky18owL.jpg',
			release_date: '2024-02-04',
			title: 'Shin Spider-Man',
			video: false,
			vote_average: 0.0,
			vote_count: 0,
		},
	],
};
